Mon Jun 24 13:02:24 CEST 2024

diff --git a/Makefile_push b/Makefile_push
--- a/Makefile_push
+++ b/Makefile_push
@@ -1,10 +1,8 @@
-NAME = so_long
-NAME_BONUS = so_long_bonus
+NAME = push_swap
+NAME_BONUS = checker
 
 CC = cc
-FLAGS = -Wextra -Wall -Werror -g -fPIE -I$(HEADER_FOLDER) -lm
-# FLAGS = -Wextra -Wall -g -fPIE
-# CFLAGS = -Wall -Werror -Wextra -g -fPIE -I$(HEADER_FOLDER) -lm
+FLAGS = -Wextra -Wall -Werror -g -fPIE
 # FLAGS = -g -fPIE
 
 all: $(NAME)
@@ -13,116 +11,58 @@ all: $(NAME)
 # │                  	 	        TESTING                    	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-# big map, 3 pika
-MAPG = good_map.ber
-# big map, 3 pika
-MAP1 = map1.ber
-# big square, no pika
-MAP2 = map2.ber
-# medium square, lots of pika
-MAP3 = map3.ber
-# small square, 1 pika
-MAP4 = map4.ber
-# only balls
-MAP5 = map5.ber
+ARGS = "1 2 3 9 8 7"
+ARGS2 = 1 6 5 7 9 4 8 33
+
+a: $(NAME)
+	@$(call print_cat_test, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), "にゃ~", "~ teshing $@!~");
+	./$(NAME) $(ARGS)
+
+b: $(NAME_BONUS)
+	@echo > outfile
+	@$(call print_cat_random, # $(COLOR_5R_3G_1B), # $(COLOR_5R_2G_3B), # $(COLOR_0R_2G_3B), "~ teshing $@! ~");
+	./$(NAME_BONUS) $(ARGS2)
 
 
-a: libft mlx $(NAME_BONUS) inc/so_long_bonus.h
-	@$(call random_shmol_cat, "\'tis good map", 'hav fun ね? (make m for testeur mandatory)', $(CLS), );
-	@echo "\tuse -WASD- or →↓←↑ to move around"
-	@echo "\tuse -SPACE- to throw ball"
-	@echo "\tpress -CTRL-l- to toogle run"
-	@echo "\tpress -E- to print memory"
-	@echo "\n\t\033[5m~ Press Enter to start, and good luck... ~\033[0m"
-	@read -p "" key
-	./$(NAME_BONUS) map/$(MAPG)
+test2:	libft $(OBJ)
+	@$(CC) $(OBJ) ./lib/test.c -I$(HEADER_FOLDER) ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_2G_5B), $(COLOR_5R_1G_1B), $(COLOR_3R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
+	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes \
+	./lib/a.out $(ARGS)
 
-b: libft mlx $(NAME_BONUS)
-	@$(call random_shmol_cat, teshting ... $@ !, " $(NAME_BONUS): ", $(CLS), );
-	-$(VALGRIND) ./$(NAME_BONUS) map/$(MAP2)
+test3:	libft $(OBJ)
+	@$(CC) $(OBJ) ./lib/test.c -I$(HEADER_FOLDER) ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_2G_5B), $(COLOR_5R_1G_1B), $(COLOR_3R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
+	./lib/a.out $(ARGS)
 
-c: libft mlx $(NAME_BONUS)
-	@$(call random_shmol_cat, teshting ... $@ !, " $(NAME_BONUS): ", $(CLS), );
-	-$(VALGRIND) ./$(NAME_BONUS) map/$(MAP5)
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - VALGRIND -
+v: $(NAME) $(NAME_BONUS)
+	@clear
+	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes \
+	./$(NAME_BONUS) $(ARGS)
 
-v: libft mlx $(NAME_BONUS)
-	@$(call random_shmol_cat, "vlgrininnng ... $(NAME_BONUS)!", "$@: $(MAP1)", $(CLS), );
-	-$(VALGRIND) ./$(NAME_BONUS) map/$(MAP1)
-	@echo $(RESET);
-
-# ---------------------------------------------------------------------- >
-BAD_MAPS = map_bad_not_rect1.ber map_no_collec.ber map_no_player.ber \
-			map_no_exit.ber map_many_exit.ber \
-			map_many_player.ber map_bad_wall.ber \
-			map_bad_enclosed_e.ber map_bad_enclosed_c.ber \
-			map_bad_tile.ber
-
-# map=$$($(eval echo $$arg));
-m: libft mlx $(NAME)
-	@for map in $(BAD_MAPS); do \
-	$(call random_shmol_cat, teshting lots of bad miaps:, $$map shouldt run..., $(CLS), ); \
-	$(VALGRIND) ./$(NAME) map/map_bad/$$map; \
-	echo "\t\033[5m~ Press Enter to continue...\033[0m"; \
-	read -p "" key; \
-	done
-#
-	@$(call shmol_cat_color, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), teshing with bad map name!, map_multiplayer.be, $(CLS), );
-	-$(VALGRIND) ./$(NAME) map/map_multiplayer.be
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key;
-	@$(call shmol_cat_color, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), teshing with bad map name!, mapzzzzz.ber, $(CLS), );
-	-$(VALGRIND) ./$(NAME) map/mapzzzzz.ber
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key
-#
-	@$(call random_shmol_cat, teshing too much args, "$(MAP1) abc", $(CLS), );
-	-$(VALGRIND) ./$(NAME) map/$(MAP1) map/$(MAP2)
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key
-#
-	@$(call shmol_cat_color, $(COLOR_5R_0G_5B), $(COLOR_5R_2G_3B), teshing with empty file, map_blank.ber, $(CLS), );
-	@echo "$(RED)"
-	touch ./map/map_blank.ber
-	@echo "$(COLOR_5R_0G_5B)"
-	-$(VALGRIND) ./$(NAME) map/map_blank.ber
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key
-#
-	@$(call shmol_cat_color, $(COLOR_5R_4G_0B), $(COLOR_5R_2G_3B), teshing with a sprite file renamed!!!, , $(CLS), );
-	@echo "$(RED)"
-	mv ./img/player/player_0.xpm ./img/player/player_007.xpm
-	@echo "$(COLOR_5R_4G_0B)"
-	-$(VALGRIND) ./$(NAME) map/$(MAP3)
-	@echo "$(RED)"
-	mv ./img/player/player_007.xpm ./img/player/player_0.xpm
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key
-#
-	@$(call random_shmol_cat, "\'tis good map Mandatory", "try n break it.. にゃ?", $(CLS), );
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key
-	-$(VALGRIND) ./$(NAME) map/$(MAP3)
-
-m2: libft mlx $(NAME)
-	@$(call random_shmol_cat, "\'tis good map Mandatory", "try n break it.. にゃ?", $(CLS), );
-	@echo "\t\033[5m~ Press Enter to continue...\033[0m"
-	@read -p "" key
-	-$(VALGRIND) ./$(NAME) map/$(MAP3)
+# lldb: clean all
+# 	@lldb ./$(NAME) $(ARGS)
 
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	        SOURCES                    	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-SRC = $(wildcard src/*.c)
-OBJ = $(patsubst src/%.c, src/obj/%.o, $(SRC))
-
 SRC_FOLDER = src
 OBJ_FOLDER = src/obj
-HEADER_FOLDER = inc
+HEADER_FOLDER = include
+
+# $(patsubst pattern,replacement,text)
+# $(addprefix prefix, list)
+SRC = $(wildcard src/*.c)
+OBJ = $(patsubst src/%.c, src/obj/%.o, $(SRC))
 
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	        Libft                      	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
+
+# -s: silent
+# -C: change folder before make
 
 libft:
 	@make -sC lib all;
@@ -140,21 +80,22 @@ libtest:
 # │                  	 	       PROJECT                   	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-$(NAME): libft $(OBJ) main.c
-	@clear
-	@if ! $(CC) $(FLAGS) $(OBJ) main.c lib/libft.a -o $(NAME); then \
-		$(call print_cat, "", $(RED), $(GOLD), $(RED_L), $(call pad_word, 10, "ERROR"), $(call pad_word, 12, "COMPILING..")); \
+$(NAME): libft main.c $(OBJ)
+	@if ! $(CC) $(FLAGS) $(OBJ) main.c -I$(HEADER_FOLDER) lib/libft.a -o $(NAME); then \
+		$(call print_cat, "", $(GOLD), $(RED), $(RED), $(call pad_word, 10, "Problem⠀while"), $(call pad_word, 12, "Compiling..")); \
 		exit 1; \
 	fi
-	$(call print_cat, $(CLEAR), $(GOLD), $(GREEN1), $(GREEN1), $(call pad_word, 10, $(NAME)), $(call pad_word, 12, "Compiled~"));
-
+	@if [ ! -e in ]; then\
+		echo > in;\
+	fi
+	$(call print_cat, $(CLEAR), $(GOLD), $(GREEN1), $(GOLD), $(call pad_word, 10, $(NAME)), $(call pad_word, 12, "Compiled~")); \
 
 src/obj/%.o: src/%.c
 	@if [ ! -e $(OBJ_FOLDER) ]; then\
 		mkdir -p $(OBJ_FOLDER);\
 	fi
-	@if ! $(CC) -c $(FLAGS) $< -o $@; then \
-		$(call shmol_cat_error, $(RED), $(RED_L)); \
+	@if ! $(CC) -c $(FLAGS) -I$(HEADER_FOLDER) $< -o $@; then \
+		$(call print_cat_error, $(RED), $(RED_L)); \
 		exit 1; \
 	fi
 
@@ -162,104 +103,58 @@ src/obj/%.o: src/%.c
 # │                  	 	       BONUS	                   	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
-SRC_B = $(wildcard src_bonus/*.c)
-OBJ_B = $(patsubst src_bonus/%.c, src_bonus/obj/%.o, $(SRC_B))
-
-OBJ_FOLDER_B = src_bonus/obj
-
-$(NAME_BONUS): bonus
-
-bonus: libft $(OBJ_B) main_bonus.c inc/so_long.h
-	@clear
-	@if ! $(CC) $(FLAGS) $(OBJ_B) main_bonus.c lib/libft.a -o $(NAME_BONUS); then \
-		$(call print_cat, "", $(RED), $(GOLD), $(RED_L), $(call pad_word, 10, "ERROR"), $(call pad_word, 12, "COMPILING..")); \
+$(NAME_BONUS): libft main_bonus.c $(OBJ)
+	@if ! $(CC) $(FLAGS) $(OBJ) main_bonus.c -I$(HEADER_FOLDER) lib/libft.a -o $(NAME_BONUS); then \
+		$(call print_cat, "", $(GOLD), $(RED), $(RED), $(call pad_word, 10, "Problem⠀while"), $(call pad_word, 12, "Compiling..")); \
 		exit 1; \
 	fi
-	$(call print_cat, $(CLEAR), $(GOLD), $(GREEN1), $(COLOR_4R_1G_5B), $(call pad_word, 10, $(NAME_BONUS)), $(call pad_word, 12, "Compiled~"));
+	@$(call print_cat, $(CLEAR), $(COLOR_5R_1G_5B), $(COLOR_1R_2G_4B), $(COLOR_5R_1G_0B), $(call pad_word, 10, $(NAME_BONUS)), $(call pad_word, 14, "All⠀ready~"));
 
-src_bonus/obj/%.o: src_bonus/%.c inc/so_long_bonus.h
-	@clear
-	@if [ ! -e $(OBJ_FOLDER_B) ]; then\
-		mkdir -p $(OBJ_FOLDER_B);\
-	fi
-	@if ! $(CC) -c $(FLAGS) -O3 -c $< -o $@; then \
-		$(call shmol_cat_error, $(RED), $(RED_L)); \
-		exit 1; \
-	fi
+bonus: $(NAME_BONUS)
 
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	       OTHERS	                   	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
 
 test:	libft
-	@rm -f ./lib/a.out
-	-@cc ./lib/test.c ./lib/libft.a -o ./lib/a.out -lm
-	@if [ ! -e ./lib/a.out ]; then\
-		$(call print_cat, "", $(RED), $(GOLD), $(RED_L), $(call pad_word, 10, "The⠀Cake"), $(call pad_word, 12, "Is⠀A⠀Lie..")); \
-		exit 3; \
-	fi
-	@$(call random_cat, $(call pad_word, 12, "Making"), $(call pad_word, 14, "Science"), $(CLS), $(RESET));
-	@lib/a.out
-
-test2:	libft $(OBJ_B)
-	@rm -f ./lib/a.out
-	@cc ./lib/test.c $(OBJ_B) -I$(HEADER_FOLDER) lib/libft.a -lm -o ./lib/a.out
-	@$(call random_cat, $(call pad_word, 12, "TESTING"), $(call pad_word, 14, "SCIENCE"), $(CLS), $(RESET));
-	-@$(VALGRIND) lib/a.out map/map4.ber
+	@$(CC) ./lib/test.c ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_0G_5B), $(COLOR_5R_1G_0B), $(COLOR_0R_2G_5B), $(call pad_word, 10, "Making"), $(call pad_word, 12, "Science"));
+	@lib/a.out $(ARGS2)
 
 vtest:	libft
-	@cc -g3 ./lib/test.c ./lib/libft.a -o ./lib/a.out -lm
-	$(call print_cat, "", $(RED), $(GOLD), $(BLUE1), $(call pad_word, 10, "TESTING"), $(call pad_word, 12, "SCIENCE.."));
-	@$(VALGRIND) lib/a.out
+	@$(CC) -g3 ./lib/test.c ./lib/libft.a -o ./lib/a.out
+	@$(call print_cat, $(CLEAR), $(RED), $(GOLD), $(BLUE1), $(call pad_word, 10, "TESTING"), $(call pad_word, 12, "SCIENCE"));
+	@valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes \
+	./lib/a.out $(ARGS)
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - CLEANUP -
 clean:
-	@rm -rf $(OBJ_FOLDER)
-	$(call print_cat, $(CLEAR), $(COLOR_2R_2G_5B), $(COLOR_3R_2G_0B), $(COLOR_4R_5G_0B), $(call pad_word, 10, "Objects"), $(call pad_word, 12, "Exterminated"));
+	@rm -rf $(OBJ_FOLDER) outfile
+	@$(call print_cat, $(CLEAR), $(COLOR_2R_2G_5B), $(COLOR_3R_2G_0B), $(COLOR_4R_5G_0B), $(call pad_word, 10, "Objects"), $(call pad_word, 12, "Exterminated"));
 
 fclean: clean
-	@rm -rf $(NAME) $(NAME_BONUS)
-	@make -sC lib clean_silent;
-	$(call print_cat, $(CLEAR), $(COLOR_1R_2G_0B), $(COLOR_3R_0G_0B), $(COLOR_2R_1G_0B), $(call pad_word, 10, "All⠀clean"), $(call pad_word, 12, "Miaster"));
+	@rm -f $(NAME) $(NAME_BONUS) in
+	@make -sC lib clean_silent
+	@rm -rf traces
+	@$(call print_cat, $(CLEAR), $(COLOR_1R_2G_0B), $(COLOR_3R_0G_0B), $(COLOR_2R_1G_0B), $(call pad_word, 10, "All⠀clean"), $(call pad_word, 12, "Miaster"));
 
 re: fclean all bonus
 
-re_bonus: fclean
-
+# .PHONY target is typically used to declare targets that are not actual files but rather are just actions to be performed by make, like clean or all.
 .PHONY: all clean fclean re bonus
 
 .SILENT: $(NAME) bonus
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - -  - -  - VALGRIND
-VALGRIND = valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --track-fds=yes
-# VALGRIND = valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s --trace-children=yes --track-fds=yes
-#
-# lldb: clean all
-# 	@lldb ./$(NAME) $(ARGS)
-#
-# ↑さ↓ぎょう  を  ↓ほ↑ぞん
-# 																	GITHUB
-git: fclean
-	@$(call random_shmol_cat_blink, 作業を保存してるかな.., いいね、いいねえー , $(CLS), );
-	@current_date=$$(date); \
-	git add .; \
-	git commit -m "$$current_date"; \
-	git push
-
-NORM_FILE = src_bonus/
-
-norm: fclean
-	@$(call random_shmol_cat_blink, 掃除してるかな..、いいね、いいねえー, giv file to norm, $(CLS), );
-	-@read -p 'file...:' path; \
-	if [ -z "$$path" ]; then \
-		watch norminette $(NORM_FILE); \
-	else \
-		watch norminette $$path; \
-	fi
-
-#
 # ╭──────────────────────────────────────────────────────────────────────╮
 # │                  	 	       PRINT                     	         │
 # ╰──────────────────────────────────────────────────────────────────────╯
+
+# U+2800 to U+28FF Braile
+# <Esc>[38;5;ColorNumberm
+
+CLEAR = \033[2J\033[H
+RESET = \033[0m
+BLINK = \033[5m
 
 # COLOR_2R_1G_3B
 PURPLE = \033[38;5;97m
@@ -270,23 +165,13 @@ GREEN1 = \033[38;5;40m
 # COLOR_0R_4G_5B
 BLUE1 = \033[38;5;45m
 
-# $(COLOR_1R_0G_5B), $(COLOR_5R_1G_0B), $(COLOR_0R_2G_5B)
-# $(RED), $(GOLD), $(BLUE1)
+test_color:
+	$(call print_cat, $(CLEAR), $(RED), $(RED1), $(RED_L), $(call pad_word, 12, "The⠀Cake"), $(call pad_word, 12, "Is⠀A⠀Lie..."));
 
-test_color666:
-	@$(call random_cat, $(call pad_word, 12, The⠀Cake), $(call pad_word, 14, Is⠀A⠀Lie⠀...), $(CLS), $(RESET));
-	@$(call random_cat, $(call pad_word, 13, The⠀Cake), $(call pad_word, 15, Is⠀A⠀Lie⠀...), , $(RESET));
-
-
-# $(call pad_word, 12, The⠀Cake)
 pad_word = $(BLINK)$(shell printf "%$(1)s" "$(2)")$(RESET)
-# improve with: STRING1=$$(printf "\033[38;5;%dm" $$(shuf -i 0-255 -n 1));
-
-# --------------------------------------------------------------------------------- >
-# @$(call print_cat, $(CLEAR), $(body), $(eye), $(txt), $(call pad_word, 12, "The⠀Cake"), $(call pad_word, 12, "Is⠀A⠀Lie..."));
 # print_cat (resest?)(color_cat)(color_eyes)(color_text)($(padded_txt_top))($(padded_txt_bot))
 define print_cat
-    @echo "$(1)$(2)\
+    echo "$(1)$(2)\
 	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠒⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n\
 	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠇⠀⠘⡄⠀⠀⠀⠀⠀⠀⣀⠀⠀\n\
 	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠁⠉⠉⠉⠒⠊⠉⠀⡇⠀\n\
@@ -305,86 +190,8 @@ define print_cat
 	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠉⠐⠒⠠⠤⠤⠤⠤⠔⠂⠠⠤⠤⠤⠄⠐⠒⠂⠉⠉⠉⠉⠉⠁\n$(RESET)"
 endef
 
-# --------------------------------------------------------------------------------- >
-# @$(call random_cat, $(call pad_word, 12, txt1), $(call pad_word, 12, txt2), $(CLS), $(RESET));
-# print_cat (resest?)(color_cat)(color_eyes)(color_text)($(padded_txt_top))($(padded_txt_bot))
-define random_cat
-	COLOR=$$(printf "\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	COLOR2=$$(printf "\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	COLOR3=$$(printf "\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-    echo "$(3)$${COLOR}\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠒⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠇⠀⠘⡄⠀⠀⠀⠀⠀⠀⣀⠀⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠁⠉⠉⠉⠒⠊⠉⠀⡇⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀$${COLOR2}$(BLINK)⣀⡀$(RESET)$${COLOR}⠀⠀⠀⠀⠀⠀⠀⠀⢰⠁⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠲⢴⠁⠀$${COLOR2}$(BLINK)⠛⠁$(RESET)$${COLOR}$${COLOR2}$(BLINK)⠀⠀⢀⣄$(RESET)$${COLOR}⠀⠀⠀⠀⢸⠀⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠑⠺⡀⠀⠀⢶⠤$${COLOR2}$(BLINK)⠀⠈⠋$(RESET)$${COLOR}⠀⠀⠀⠀⡘⠀⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⡀⠀⠀⠀⠠⣉⠑⠂⠀⢠⠃⠀⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠊⠀⠀⠀⠀⠀⠀⠁⠀⠀⠈⢆⠀⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⡆⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠤⠒⠒⠃⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⠀\n\
-	\t\t\t\t\t\t\t	⠀⠔⠑⠄⠀⠀⠀⠀⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇\n\
-	\t\t\t\t\t\t\t	⠸⡀⠀⢣⠀⠀⠀⠀⠀⠀⠀⠀⡇$${COLOR3}$(1)$${COLOR}⠀⠀⠀⠀⠀⡇\n\
-	\t\t\t\t\t\t\t	⠀⠱⡀⠀⠳⡀⠀⠀⠀⠀⠀⠀⢃$${COLOR3}$(2)$${COLOR}⠀⠀⡸⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠑⢄⠀⠈⠒⢄⡀⠀⠀⠀⠸⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠁⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠑⠦⣀⠀⠈⠉⠐⠒⠒⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⢢⠀\n\
-	\t\t\t\t\t\t\t	⠀⠀⠀⠀⠀⠀⠀⠉⠐⠒⠠⠤⠤⠤⠤⠔⠂⠠⠤⠤⠤⠄⠐⠒⠂⠉⠉⠉⠉⠉⠁\n$(4)"
-endef
-
-# --------------------------------------------------------------------------------- >
-# @$(call shmol_cat_color, $(color_cat), $(color_txt), text1, txt2, $(CLS), $(RESET));
-define shmol_cat_color
-	echo "$(5)$(2)\
-	\tにゃ~$(1)\t⠀╱|、\n\
-	\t\t(˚ˎ。7⠀⠀⠀$(2)~ $(3) ~$(1)\n\
-	\t\t⠀|、˜\\\\\t\t$(2)$(4)$(1)\n\
-	\t\t⠀じしˍ)ノ\n$(6)"
-endef
-# --------------------------------------------------------------------------------- >
-# @$(call random_shmol_cat, text 1, text 2, $(CLS), $(RESET));
-# $(1)= $(CLEAR); $(2)= text1; $(3)= text2; $(4)= $(RESET)
-define random_shmol_cat
-	COLOR=$$(printf "\033[38;5;%dm" $$(shuf -i 1-255 -n 1)); \
-	COLOR2=$$(printf "\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	echo "$(3)$${COLOR2}\
-	\tにゃ~$${COLOR}\t⠀╱|、\n\
-	\t\t(˚ˎ。7⠀⠀⠀$${COLOR2}~ $(1) ~$${COLOR}\n\
-	\t\t⠀|、˜\\\\\t\t$${COLOR2}~ $(2)$${COLOR}\n\
-	\t\t⠀じしˍ)ノ\n$(4)"
-endef
-
-# // <!> - - - - - - - - - - - </!>
-# --------------------------------------------------------------------------------- >
-rscs:
-	@$(call random_shmol_cat_surligne, text 1, text 2, $(CLS), $(RESET));
-
-define random_shmol_cat_surligne
-	COLOR=$$(printf "\033[0m\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	COLOR2=$$(printf "\033[48;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	echo "$(3)$${COLOR2}\
-	\tにゃ~$${COLOR}\t⠀╱|、\n\
-	\t\t(˚ˎ。7⠀⠀⠀$${COLOR2}~ $(1) ~$${COLOR}\n\
-	\t\t⠀|、˜\\\\\t\t$${COLOR2}~ $(2)$${COLOR}\n\
-	\t\t⠀じしˍ)ノ\n$(4)"
-endef
-
-rscb:
-	@$(call random_shmol_cat_blink, text 1, text 2, $(CLS), $(RESET));
-
-define random_shmol_cat_blink
-	COLOR=$$(printf "\033[0m\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	COLOR2=$$(printf "\e[5m\033[38;5;%dm" $$(shuf -i 0-255 -n 1)); \
-	echo "$(3)\n$${COLOR2}\
-	\tにゃ~$${COLOR}\t⠀╱|、\n\
-	\t\t(˚ˎ。7⠀⠀⠀$${COLOR2}~ $(1) ~$${COLOR}\n\
-	\t\t⠀|、˜\\\\\t\t$${COLOR2}~ $(2)$${COLOR}\n\
-	\t\t⠀じしˍ)ノ\n$(4)"
-endef
-# // <!> - - - - - - - - - - - </!>
-# --------------------------------------------------------------------------------- >
-# @$(call shmol_cat_error, $(RED), $(RED_L));
-# $(1) = $(color_cat), $(2) = $(color_text)	NO CLS
-define shmol_cat_error
+# $(call print_cat_error, $(RED), $(RED_L));
+define print_cat_error
 	echo "$(2)\
 	\tにゃ~$(1)\t⠀╱|、\n\
 	\t\t(˚ˎ。7⠀⠀⠀$(2)~ somshin wen wong ~$(1)\n\
@@ -392,13 +199,42 @@ define shmol_cat_error
 	\t\t⠀じしˍ)ノ\n$(RESET)"
 endef
 
+# $(call print_cat_test, $(COLOR_5R_3G_1B), $(COLOR_0R_2G_3B), $@, "~ teshing $@! ~");
+define print_cat_test
+	echo "$(CLEAR) $(2)\
+	\t$(3)$(1)\t⠀╱|、\n\
+	\t\t(˚ˎ。7⠀⠀⠀$(2)$(4)$(1)\n\
+	\t\t⠀|、˜\\\\\n\
+	\t\t⠀じしˍ)ノ\n$(RESET)"
+endef
+
+# $(call print_cat_random, # $(random_color), # $(random_color), # $(random_color), "~ teshing $@! ~");
+define print_cat_random
+	echo "$(CLEAR) $(2)\
+	\tにゃ~$(1)\t⠀╱|、\n\
+	\t\t(˚ˎ。7⠀⠀⠀$(3)$(4)$(1)\n\
+	\t\t⠀|、˜\\\\\n\
+	\t\t⠀じしˍ)ノ\n$(RESET)"
+endef
+
+# //////////////////////////////////////
+# @echo "Random color escape sequence: $(call random_color_escape)"
+# Define a function to generate a random color code
+define random_colora
+	\033[38;5;$(shell echo $$((RANDOM % 256)))m
+endef
+
+random_number := $(shell od -An -N1 -tu1 /dev/urandom)
+
+define random_number_func
+	$(random_number)
+endef
+
+random_number:
+	@echo $(random_number)
+
+# //////////////////////////////////////
 # 					Define all 256 colors
-CLEAR = \033[2J\033[H
-CLS = \033[2J\033[H
-RESET = \033[0m
-BLINK = \033[5m
-# U+2800 to U+28FF Braile
-# <Esc>[38;5;ColorNumberm
 BLACK = \033[38;5;0m
 RED = \033[38;5;1m
 GREEN = \033[38;5;2m
